version: '3.8'

volumes:
  postgres-data:

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
        # Ensure that the variables in .env match the same variables in devcontainer.json
        - .env

    volumes:
      - ../..:/workspaces:cached
      
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:neo4j

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  neo4j:
    image: neo4j:5-community
    restart: unless-stopped
    volumes:
      - $HOME/neo4j/data:/data
    env_file:
      # Ensure that the variables in .env match the same variables in devcontainer.json
      - .env
    ports:
      - 7474:7474
      - 7687:7687
  
  ollama:
    # image: ollama/ollama
    build: 
      context: .
      dockerfile: ollama.Dockerfile
    restart: unless-stopped
    volumes:
      - $HOME/ollama:/root/.ollama
    env_file:
      # Ensure that the variables in .env match the same variables in devcontainer.json
      - .env
    ports:
      - 11434:11434
    # command: ollama run codellama

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
